spring:
  application:
    name: house-rental
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
  sql:
    init.mode: embedded
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  error.include-stacktrace: never

jwt:
  secret: ${JWT_SECRET}

app:
  pagination:
    default-page-size: 10
    default-page-number: 0
    max-page-size: 20


cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}

vnpay:
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}

base:
  server-url: http://localhost:8080/
  client-url: http://localhost:3000/