spring:
  application:
    name: house-rental
  datasource:
    url: jdbc:mysql://localhost:3306/house_rental?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/house_rental?allowPublicKeyRetrieval=true&useSSL=false
    user: root
    password: root
  jpa:
    hibernate.ddl-auto: none
  sql:
    init.mode: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: huy.th878@aptechlearning.edu.vn
    password: ivyuiosiserxuxce
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  error.include-stacktrace: never

jwt:
  secret: superSerectJwt1234567890!@#$%^&*()_+superSerectJwt1234567890!@#$%^&*()_+

app:
  pagination:
    default-page-size: 10
    default-page-number: 0
    max-page-size: 20

