ALTER TABLE users
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE roles
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE authorities
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE cities
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE districts
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE properties
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE amenities
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE property_images
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE reviews
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE favorites
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE advertisements
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE reports
MODIFY COLUMN is_deleted BOOLEAN DEFAULT FALSE;
