DROP TABLE IF EXISTS cities;
CREATE TABLE IF NOT EXISTS cities
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS districts;
CREATE TABLE IF NOT EXISTS districts
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    city_id    INT,
    created_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE CASCADE ON UPDATE CASCADE
);
