DROP TABLE IF EXISTS room_types;
CREATE TABLE IF NOT EXISTS room_types
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP
);
