name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up environment variables
        run: |
          echo CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> .env
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env
          echo USERNAME_EMAIL=${{ secrets.USERNAME_EMAIL }} >> .env
          echo PASSWORD_EMAIL=${{ secrets.PASSWORD_EMAIL }} >> .env
          echo DB_URL=${{ secrets.DB_URL }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo VNPAY_TMN_CODE=${{ secrets.VNPAY_TMN_CODE }} >> .env
          echo VNPAY_HASH_SECRET=${{ secrets.VNPAY_HASH_SECRET }} >> .env

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sosovi/house_rental:latest .


      - name: Verify Docker image
        run: docker images sosovi/house_rental:latest

      - name: Push Docker image
        run: docker push sosovi/house_rental:latest

      - name: Deploy to Render
        run: |
          curl -X POST -H "Accept: application/json" ${{ secrets.RENDER_DELOY_HOOK }}